# Licensed under a 3-clause BSD style license - see LICENSE.rst
import sys

# Time constants (all in seconds unless noted)
SECONDS_PER_DAY = 86400
HALF_DAY_SECONDS = 43200  # Minimum GTI duration for valid processing
SECONDS_PER_MONTH = SECONDS_PER_DAY * 30
SECONDS_PER_YEAR = SECONDS_PER_DAY * 365.25

# Mission timeline constants (MET values)
# MET when science operations began (end of commissioning phase)
SCIENCE_START_MET = 77674700

__all__ = ["__version__"]
# NOTE: First try _version if it exists and was generated by setuptools_scm
# This file provides the version for the package.
try:
    from ._version import version
except ImportError:
    import warnings

    warnings.warn(
        f'could not determine {__name__.split(".")[0]} package version; '
        'this indicates a broken installation'
    )
    del warnings

    version = '0.0.0'

__version__ = version


def log_execution():
    from astropy import log
    if len(sys.argv) > 1:
        args_str = "args: " + ' '.join(sys.argv[1:])
    else:
        args_str = "no arguments"

    log.info(f"This is nuclockutils v.{__version__}")
    log.info(f"Executing {os.path.basename(sys.argv[0])} with {args_str}")

from .nustarclock import *
from .utils import *
from .barycorr import *
